### ISSUE TITLE
Downloading large audiobooks 

### ISSUE THREAD

**Issue by martiege** [mkb79/audible-cli#150]
I have some problems when trying to download larger audiobooks, specifically when using the `--aax-fallback` flag. These books cannot be downloaded as `.aax` files, while `.aaxc` works, however when I try to download these files I get this error: 

```bash 
error: Error downloading /audiobooks/The_Rise_and_Fall_of_the_Third_Reich_A_History_of_Nazi_Germany-LC_64_22050_stereo.aax. Wrong content type. Expected type(s): ['audio/aax', 'audio/vnd.audible.aax', 'audio/audible']; Got: text/html;charset=UTF-8; Message: This title is not supported for full audio file download, please download individual parts.
```

I would expect the program here to try downloading the `.aaxc` file, however this doesn't seem to happen. 

I'm still on v0.2.4 if this might be relevant.

**Comment by mkb79** [comment]
The `aax-fallback` currently only applies if the book is marked as an AYCE title or the requested codec is not supported via AAX. Both criteria are not met in the present case. As a result, there is no fallback to aaxc. 

I've take a look deeper into this title. There are no indications in the api metadata that this title only supports partial download as AAX file. So with such books, you must first try to download them to find that only a partial download is possible. This can be implemented in `audible-cli` but need some extra work!

For this and other reasons, I would advise you to only download books in AAXC format.

**Comment by martiege** [comment]
Thank you for the reply! This happened to a couple of other titles as well, specifically for very large audiobooks where the API seems to return that `text/html;charset=UTF-8; Message: This title is not supported for full audio file download, please download individual parts.` reply rather than the expected `.aax` file. 

As this could be considered a bug, maybe this issue should be kept up? 

I'll just move over to only using `.aaxc` from now, as you advise!

**Comment by mkb79** [comment]
I'll have three options now:

1. extend the fallback to download aaxc books in that case,
2. download the audiobook in parts in aax format or
3. leave it unchanged. 

I'll think option 3 is the best (Time-saving)! There are no differences between aax and aaxc files except the encryption method. After removing the encryption, they are absolute identical.

**Comment by devnoname120** [comment]
@mkb79
1. We know that there are books that are available as `AAXC` but _not_ `AAX` (hence the `--aax-fallback` flag).
2. Conversely, are we actually 100% sure that there are no books that are available as `AAX` but _not_ `AAXC`? i.e. books that would fail to download when using `--aaxc` even though they work with `--aax`.

**Comment by mkb79** [comment]
@devnoname120 

`AAXC` and `AAX` are container files like `M4A` or `MKV`. They contain the encrypted audiofile, cover and metadata. The encryption algorithm used is also the same. 

In order not to go too far into technical details, one can generally said:

- aax use only one key per user for all audiobook
- aaxc use one key/iv pair per user and audiobook.

`AAXC` exists since some time to prevent decrypting all audiobooks with a single key. It is also possible to derive the key from an `AAX` audiobook if someone has uploaded the audiobook to the Internet. Audible had to protect his `AYCL` and Audible Plus service. 

Since introducing `AAXC`, a license request to the Audible API will not deliver `AAX` files anymore. However, there is still an unofficial way for bypassing the API to download it in `AAX` for certain audio books and if you have purchased this book.

To answer your second question, all newer Audible clients (including the iOS and Android app) only use the official way via the API licenserequest. Audible not only delivers AAXC audiobooks via the API, some unprotected ones are also downloadable as MPG or other formats. And Audible encrypt the audiofile on the fly when downloading the book. 
Therefore, I am 99.99% sure that all books can be downloaded via the API licenserequest. 

The only advantage using AAX is the simple decryption since you only have to find out the user key once. With AAXC you have to keep the key/iv beside the encrypted audiobook, otherwise your encrypted audiobook is useless.

**Comment by mkb79** [comment]
Maybe someone can test out this [branch](https://github.com/mkb79/audible-cli/tree/150-downloading-large-audiobooks) if it downloads audiobook parts.

**Comment by martiege** [comment]
Nice, I'll try to remember to test it 😊
