### ISSUE TITLE
Doesn't support accounts where two-factor is implicitly enabled

### ISSUE THREAD

**Issue by aikinai** [mkb79/audible-cli#6]
Hello,

First of all, this software is amazing; thank you so much for making such a robust and easy-to-use Audible interface!

But I wanted to report that I had some trouble logging into my account with `audible-quickstart`. I do not have two-factor enabled on my account, and as expected, Amazon does not require a second factor when I log in. However, Audible specifically does seem to implicitly require two-factor for every login. It always sends an SMS to my phone number and a notification to my Amazon app and I can't find anywhere to disable it since two-factor is not enabled. This would cause `audible-quickstart` to fail with the following trace after passing the captcha. I get the notification and SMS, but `audible-quickstart` fails before I can allow the login. It's a Japanese account by the way; maybe that's a special policy in that region?

```
Traceback (most recent call last):
  File "~/Library/Python/3.8/bin/audible-quickstart", line 8, in <modu
le>
    sys.exit(quickstart())
  File "~/Library/Python/3.8/lib/python/site-packages/click/core.py",
line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/click/core.py",
line 782, in main
    rv = self.invoke(ctx)
  File "~/Library/Python/3.8/lib/python/site-packages/click/core.py",
line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/Library/Python/3.8/lib/python/site-packages/click/core.py",
line 610, in invoke
    return callback(*args, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/click/decorators
.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/audible_cli/cli.
py", line 48, in quickstart
    ctx.forward(cmd_quickstart.cli)
  File "~/Library/Python/3.8/lib/python/site-packages/click/core.py",
line 628, in forward
    return self.invoke(cmd, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/click/core.py",
line 610, in invoke
    return callback(*args, **kwargs)
    return callback(*args, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/click/decorators
.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/click/decorators
.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/click/core.py",
line 610, in invoke
    return callback(*args, **kwargs)
  File "~/Library/Python/3.8/lib/python/site-packages/audible_cli/cmd_
quickstart.py", line 145, in cli
    build_auth_file(
  File "~/Library/Python/3.8/lib/python/site-packages/audible_cli/util
s.py", line 62, in build_auth_file
    auth = LoginAuthenticator(
  File "~/Library/Python/3.8/lib/python/site-packages/audible/auth.py"
, line 351, in __init__
    resp = login(
  File "~/Library/Python/3.8/lib/python/site-packages/audible/login.py
", line 230, in login
    raise Exception("Unable to login")
Exception: Unable to login
```

I saw you do support two-factor login, so I worked around the issue by enabling explicit two-factor, running `audible-quickstart` and then disabling it again. So I'm fine for now, but I just wanted to report so that you are aware of the issue.

Thank you!

**Comment by mkb79** [comment]
Hi,

Thank you for using this software and for opening this issue. 

My package rebuild the login process of the Audible App for iOS. But I can’t rebuild the process completely. The Audible App creates and send some special cookies when requesting the login page. I think, because of missing this initial cookies, Amazon detects some abnormally activities. That must be the reason why you will be asked for a captcha and a „second“ code for verification. My package detects the request for the „second“ code by parsing the html code. This works for 2FA-enabled accounts very well. If 2FA is disabled, this package searches for a `cvf code requests` in the html code.

If a cvf is requested the hmtl code contains a „div“ tag with id „cvf-page-content“ on the German html page. This works for me in the past. Maybe the id in the html page in your country is named differently or amazon changes something in the meantime globally?! So this package don’t detect the cvf request correctly. 

I enabled 2FA for a while, so I didn’t notice this issue. I will look on it, if this happens for me, when I disable 2FA.

**Comment by aikinai** [comment]
Thanks for the explanation! It's actually not just your software; I noticed that no matter where I login, it's been forcing me to use the external authentication. Maybe it's a regional thing, or something suspicious about my account or my clients?

It might be helpful to include a note in the readme or help text that enabling two-factor works in this situation.

**Comment by mkb79** [comment]
I‘ve deactivated 2FA for my account to test the login process. I tried it several times with my german and my us amazon account. Login runs fine *without* asking for a „second“ (cvf) code. I can’t try login to japanese amazon because I have no account there. So I can‘t replay your issue at this moment.

**Comment by aikinai** [comment]
Oh okay, thanks for trying. Maybe it's something special for my account, but at least I was able to work around it, so I'm fine anyway. If I were better with Python and web automation, I'd try to debug it, but unfortunately I wouldn't know how to work on it.

Feel free to close this if you like.

**Comment by mkb79** [comment]
Okay I will close this now. 

PS:
I‘ve posted a script to replace titles from ffmetadata for you in issue-7. Maybe this helps you
